version: "3.5"

services:
  api1: &api
    container_name: api1
    hostname: api1
    image: matheusmcamargo/rinha-api:latest
    working_dir: /opt/rinha
    command:
      - -port=8080
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./api:/opt/rinha/api
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "97MB"

  api2:
    <<: *api
    container_name: api2
    command:
      - -port=8080
    hostname: api2
    ports:
      - 8082:8080

  lb:
    image: nginx
    hostname: lb
    container_name: lb
    ports:
      - 9999:9999
    volumes:
      - ./nginx:/etc/nginx
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  db:
    image: postgres:latest
    hostname: db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    command:
      - postgres
      - -c
      - config_file=/docker-entrypoint-initdb.d/postgresql.conf
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "256MB"
