version: "3.5"

services:
  api_1:
    container_name: api1
    hostname: api1
    working_dir: /opt/rinha
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    volumes:
      - ./api:/opt/rinha/api

  api_2:
    container_name: api2
    hostname: api2
    working_dir: /opt/rinha
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - PORT=8082
    ports:
      - 8082:8082
      - 9040:9040 # debugger port
    volumes:
      - ./api:/opt/rinha/api

  lb:
    image: haproxy
    hostname: lb
    container_name: lb
    ports:
      - 9999:9999
    volumes:
      - ./haproxy:/usr/local/etc/haproxy

  db:
    image: postgres:latest
    hostname: db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
