version: "3.5"

services:
  api1:
    container_name: api1
    hostname: api1
    working_dir: /opt/rinha
    command:
      - -port=8081
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      - PORT=8081
    ports:
      - 8081:8081
    volumes:
      - ./api:/opt/rinha/api
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "155MB"

  api2:
    container_name: api2
    hostname: api2
    working_dir: /opt/rinha
    command:
      - -port=8082
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8082:8082
    volumes:
      - ./api:/opt/rinha/api
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "155MB"

  lb:
    image: nginx
    hostname: lb
    container_name: lb
    ports:
      - 9999:9999
    volumes:
      - ./nginx:/etc/nginx
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "130MB"

  db:
    image: postgres:latest
    hostname: db
    container_name: db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
