version: "3.5"

services:
  api1: &api
    container_name: api1
    platform: linux/amd64
    hostname: api1
    image: matheusmcamargo/rinha-api:ledger
    working_dir: /opt/rinha
    command:
      - -port=8080
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - db-data:/db
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "97MB"
    depends_on:
      - sqlite_initializer

  api2:
    <<: *api
    container_name: api2
    command:
      - -port=8080
    hostname: api2

  lb:
    image: nginx
    hostname: lb
    container_name: lb
    ports:
      - 9999:9999
    volumes:
      - ./nginx:/etc/nginx
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "100MB"

  sqlite_initializer:
    container_name: sqlite_initializer
    build:
      context: .
      dockerfile: ./sqlite/Dockerfile
    volumes:
      - db-data:/db

volumes:
  db-data:
    name: db-data

  # db:
  #   image: postgres:latest
  #   hostname: db
  #   container_name: db
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=admin
  #     - POSTGRES_DB=rinha
  #   command:
  #     - postgres
  #     - -c
  #     - config_file=/docker-entrypoint-initdb.d/postgresql.conf
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./db:/docker-entrypoint-initdb.d
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: "0.55"
  #         memory: "256MB"
